# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris_ekranı_Qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 60, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 55, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_giris_yap = QtWidgets.QPushButton(Form)
        self.pushButton_giris_yap.setGeometry(QtCore.QRect(180, 190, 93, 28))
        self.pushButton_giris_yap.setObjectName("pushButton_giris_yap")
        self.lineEdit_kullanici_adi = QtWidgets.QLineEdit(Form)
        self.lineEdit_kullanici_adi.setGeometry(QtCore.QRect(180, 60, 113, 22))
        self.lineEdit_kullanici_adi.setObjectName("lineEdit_kullanici_adi")
        self.lineEdit_sifre = QtWidgets.QLineEdit(Form)
        self.lineEdit_sifre.setGeometry(QtCore.QRect(180, 100, 113, 22))
        self.lineEdit_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.pushButton_kaydol = QtWidgets.QPushButton(Form)
        self.pushButton_kaydol.setGeometry(QtCore.QRect(180, 230, 93, 28))
        self.pushButton_kaydol.setObjectName("pushButton_kaydol")
        self.label_bildiri_girisEkrani = QtWidgets.QLabel(Form)
        self.label_bildiri_girisEkrani.setGeometry(QtCore.QRect(190, 150, 81, 21))
        self.label_bildiri_girisEkrani.setText("")
        self.label_bildiri_girisEkrani.setObjectName("label_bildiri_girisEkrani")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Kullanıcı Adı"))
        self.label_2.setText(_translate("Form", "Şifre"))
        self.pushButton_giris_yap.setText(_translate("Form", "Giriş Yap"))
        self.pushButton_kaydol.setText(_translate("Form", "Kaydol"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
