# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kitap_oneri_Qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(431, 346)
        self.pushButton_oner_kitapOner = QtWidgets.QPushButton(Form)
        self.pushButton_oner_kitapOner.setGeometry(QtCore.QRect(160, 210, 101, 31))
        self.pushButton_oner_kitapOner.setObjectName("pushButton_oner_kitapOner")
        self.label_isim_kitapOner = QtWidgets.QLabel(Form)
        self.label_isim_kitapOner.setGeometry(QtCore.QRect(100, 80, 55, 16))
        self.label_isim_kitapOner.setObjectName("label_isim_kitapOner")
        self.label_yazar_kitapOner = QtWidgets.QLabel(Form)
        self.label_yazar_kitapOner.setGeometry(QtCore.QRect(100, 120, 55, 16))
        self.label_yazar_kitapOner.setObjectName("label_yazar_kitapOner")
        self.label_katagori_kitapOner = QtWidgets.QLabel(Form)
        self.label_katagori_kitapOner.setGeometry(QtCore.QRect(100, 160, 55, 16))
        self.label_katagori_kitapOner.setObjectName("label_katagori_kitapOner")
        self.lineEdit_isim_kitapOner = QtWidgets.QLineEdit(Form)
        self.lineEdit_isim_kitapOner.setGeometry(QtCore.QRect(200, 80, 113, 22))
        self.lineEdit_isim_kitapOner.setObjectName("lineEdit_isim_kitapOner")
        self.lineEdit_yazar_kitapOner = QtWidgets.QLineEdit(Form)
        self.lineEdit_yazar_kitapOner.setGeometry(QtCore.QRect(200, 120, 113, 22))
        self.lineEdit_yazar_kitapOner.setObjectName("lineEdit_yazar_kitapOner")
        self.lineEdit_katagori_kitapOner = QtWidgets.QLineEdit(Form)
        self.lineEdit_katagori_kitapOner.setGeometry(QtCore.QRect(200, 160, 113, 22))
        self.lineEdit_katagori_kitapOner.setObjectName("lineEdit_katagori_kitapOner")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_oner_kitapOner.setText(_translate("Form", "ÖNER"))
        self.label_isim_kitapOner.setText(_translate("Form", "İsim"))
        self.label_yazar_kitapOner.setText(_translate("Form", "Yazar"))
        self.label_katagori_kitapOner.setText(_translate("Form", "Katagori"))
        self.label.setText(_translate("Form", "KİTAP ÖNERİSİ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
